//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kindergarten.ApplicationDate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Child
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Child()
        {
            this.Visit = new HashSet<Visit>();
        }
    
        public int idСhild { get; set; }
        public string Surname { get; set; }
        public string NameChild { get; set; }
        public string Patronymic { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Gender { get; set; }
        public int idParent { get; set; }
        public int idGroup { get; set; }
        public Nullable<bool> TheFamilyIsNotComplete { get; set; }
        public int idMedicalCard { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual MedicalCard MedicalCard { get; set; }
        public virtual Parent Parent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visit> Visit { get; set; }
    }
}
