//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kindergarten.ApplicationDate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public int idVisit { get; set; }
        public int idChild { get; set; }
        public System.DateTime Date { get; set; }
        public string Status { get; set; }
        public string ReasoneOfAbsence { get; set; }
    
        public virtual Child Child { get; set; }
    }
}
